Add Flow Diagram blog post
elyssonmr/blog pull request #4
Opened 2024-02-14 02:34 UTC by elyssonmr

2024-02-14 02:58 UTC, erikopa requested changes

2024-02-14 02:58 UTC, erikopa commented on content/posts/02_por_que_documentar_antes.md
> +Na teoria parece bem simples, mas é dai que você se engana. A parte mais dificil aqui é determinar o prazo para desligar a versão antiga. Se o cliente for um bom cliente e estiver trazendo um faturam
```suggestion
Na teoria parece bem simples, mas é dai que você se engana. A parte mais dificil aqui é determinar o prazo para desligar a versão antiga. Se o cliente for um bom cliente e estiver trazendo um faturamento interessante para a empresa, ele automaticamente ganha o poder de negociar esse prazo. Não é nem um pouco interessante perder esse cliente e o custo em manter a versão antiga pode ser menor do que o valor que ele está pagando por utilizar o sistema. Essa negociação de prazo normalmente é bem tensa e complicada de chegar em um concensso. Eu já trabalhei em um time que conseguimos renegociar a data limite da depreciação de uma versão da API que tinhamos um contrato de utilização. Para vocês terem uma ideia estavamos cerca de **25 versões atrás da atual**, tivemos esse poder pois eramos um bom cliente e eles não queria perder o faturamento que levavamos para a empresa deles. O argumento utilizado para extender foi que não tinhamos disponibilidade para evoluir a versão e que se não fosse mais disponibilizada usariamos outro fornecedor que também tinhamos contrato (este outro fornecedor recebia um volume bem menor de chamadas) até conseguirmos realizar a atualização. Sendo bem honesto não foi planejada essa atualização por pelo menos uns 6 meses após o prazo limite do fornecedor. Eventualmente conseguimos atualizar, mas não foi uma tarefa fácil e nem foi rapidamente priorisada. Deu muito trabalho atualizar, foi alterado inclusive o funcionamento da API, teriamos que realizar mudanças bem expressivas na aplicação. Não posso mentir sobre termos considerado não atualizar e trocar o fornecedor principal, essa hipótese passou pela cabeça de todo mundo do time.
```

2024-02-14 02:58 UTC, erikopa commented on content/posts/2024_01_18_flows_diagram.md
> +O cenário vai ser um site de delivery de delivery de comida. Os cliente irão acessar o site para realizar selecionar quais pratos desejam, realizar o pedido e pagar pelo pedido. O nome fictício do no
```suggestion
O cenário vai ser um site de delivery de comida. Os clientes irão acessar o site para selecionar quais pratos desejam, realizar o pedido e pagar pelo pedido. O nome fictício do nosso site será **LanchePlus** (usei esse nome em um sistema durante minha última experiência dando aula). Além disso vamos nos conectar com sistemas externos para poder realizar as cobranças dos pedidos dos clientes.
```

2024-02-14 02:58 UTC, erikopa commented on content/posts/2024_01_18_flows_diagram.md
> +O primeiro que vamos exemplificar é de um cliente acessando o site para escolher um prato e realizar o pedido. Neste fluxo não irá envolver somente micro-serviços, também será envolvido o cliente e o
```suggestion
O primeiro que vamos exemplificar é de um cliente acessando o site para escolher um prato e realizar o pedido. Este fluxo não irá envolver somente micro-serviços, também será envolvido o cliente e os sistemas externos que processam o pagamento. Não iremos considerar os funcionários da lanchonete pois cada lanchonete pode ter um processo muito distinto, ok??
```

2024-02-14 09:29 UTC, rhinoandre commented on content/posts/02_por_que_documentar_antes.md
> +Na teoria parece bem simples, mas é dai que você se engana. A parte mais dificil aqui é determinar o prazo para desligar a versão antiga. Se o cliente for um bom cliente e estiver trazendo um faturam
> O argumento utilizado para extender foi que não tinhamos disponibilidade para evoluir a versão e que se não fosse mais disponibilizada usariamos outro fornecedor que também tinhamos contrato (este outro fornecedor recebia um volume bem menor de chamadas) até conseguirmos realizar a atualização.

O argumento utilizado para extender foi que não tínhamos disponibilidade para evoluir a versão e que se não fosse mais disponibilizada usaríamos outro fornecedor que também tínhamos contrato, uma vez que este outro fornecedor recebia um volume bem menor de chamadas, até conseguirmos realizar a atualização.

2024-02-14 09:33 UTC, rhinoandre commented on content/posts/02_por_que_documentar_antes.md
> +Espero que este post tenha sido útil para você pelo menos considerar alguma forma diferente de fazer caso tenha passado pelos mesmos problemas que passei com relação a criar documentações posteriores
>Espero que este post tenha sido útil para você pelo menos considerar alguma forma diferente de fazer caso tenha passado pelos mesmos problemas que passei com relação a criar documentações posteriores a conclusão do desenvolvimento da aplicação. Compartilhe suas experiências sobre este tema nos comentários. Caso tenha feedbacks serão todos bem vindos também!

Espero que este post tenha sido útil, pelo menos considerar alguma alternativa caso tenha passado pelos mesmos problemas que passei com relação a criar documentações posteriores a conclusão do desenvolvimento da aplicação. Compartilhe suas experiências sobre este tema nos comentários. Caso tenha feedbacks serão todos bem vindos também!

2024-02-16 00:40 UTC, elyssonmr commented on content/posts/02_por_que_documentar_antes.md
> +Na teoria parece bem simples, mas é dai que você se engana. A parte mais dificil aqui é determinar o prazo para desligar a versão antiga. Se o cliente for um bom cliente e estiver trazendo um faturam
Valheu!!

2024-02-16 00:40 UTC, elyssonmr commented on content/posts/02_por_que_documentar_antes.md
> +Na teoria parece bem simples, mas é dai que você se engana. A parte mais dificil aqui é determinar o prazo para desligar a versão antiga. Se o cliente for um bom cliente e estiver trazendo um faturam
Valheu!!

2024-02-16 00:41 UTC, elyssonmr commented on content/posts/02_por_que_documentar_antes.md
> +Espero que este post tenha sido útil para você pelo menos considerar alguma forma diferente de fazer caso tenha passado pelos mesmos problemas que passei com relação a criar documentações posteriores
Valheu!

2024-02-16 00:42 UTC, elyssonmr commented on content/posts/2024_01_18_flows_diagram.md
> +O primeiro que vamos exemplificar é de um cliente acessando o site para escolher um prato e realizar o pedido. Neste fluxo não irá envolver somente micro-serviços, também será envolvido o cliente e o
Valheu!

2024-02-16 00:42 UTC, elyssonmr commented on content/posts/2024_01_18_flows_diagram.md
> +O cenário vai ser um site de delivery de delivery de comida. Os cliente irão acessar o site para realizar selecionar quais pratos desejam, realizar o pedido e pagar pelo pedido. O nome fictício do no
Valheu!

2024-02-16 00:43 UTC, merged